### ISSUE TITLE
Question about the distance in ply

### ISSUE THREAD

**Issue by Linkersem** [YvanYin/Metric3D#44]
Hi,Thanks for your greate work!
I find that when measure the distance near the postion i capture the image(~2m) is lager than position far away (~17m);
the near postion's difference with ground truth is about 0.1m;
the far postion's difference with ground truth is about 0.05m;
I am very confused about this?

**Comment by JUGGHM** [comment]
> Hi,Thanks for your greate work! I find that when measure the distance near the postion i capture the image(~2m) is lager than position far away (~17m); the near postion's difference with ground truth is about 0.1m; the far postion's difference with ground truth is about 0.05m; I am very confused about this?

It is not the common case (Further positions should suffer from larger errors). But in general I think the error in your case is acceptable (around 5%)?

**Comment by Linkersem** [comment]
Emmm,the far position is acceptable, the truth is ~1.12m, the .ply measured is ~1.17m, and the near position is had to say, the truth is ~0.42m, the .ply measured is ~0.56m

**Comment by JUGGHM** [comment]
> Emmm,the far position is acceptable, the truth is ~1.12m, the .ply measured is ~1.17m, and the near position is had to say, the truth is ~0.42m, the .ply measured is ~0.56m

If you can collect a small number of depth maps by depth sensors, we recommend that you use scale alignment or scale+shift alignment. Afterward, you could use such factors for further inference. We can do that because normally for the same camera, the error distribution should be similar.

If not, you might wait for a few weeks then. We will release stronger models.
